<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <base href="/">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- TemplateBeginEditable name="doctitle" -->
    <title>Untitled Document</title>
    <!-- TemplateEndEditable -->
    <!-- TemplateBeginEditable name="head" -->
    <!-- TemplateEndEditable -->
    <style type="text/css">
        <!--
        body {
            font: 100%/1.4 Verdana, Arial, Helvetica, sans-serif;
            background: #FFF;
            margin: 0;
            padding: 0;
            color: #000;
            background-color: #FFF;
        }

        /* ~~ Element/tag selectors ~~ */
        ul, ol, dl { /* Due to variations between browsers, it's best practices to zero padding and margin on lists. For consistency, you can either specify the amounts you want here, or on the list items (LI, DT, DD) they contain. Remember that what you do here will cascade to the .nav list unless you write a more specific selector. */
            padding: 0;
            margin: 0;
        }
        h1, h2, h3, h4, h5, h6, p {
            margin-top: 0;	 /* removing the top margin gets around an issue where margins can escape from their containing div. The remaining bottom margin will hold it away from any elements that follow. */
            padding-right: 15px;
            padding-left: 15px; /* adding the padding to the sides of the elements within the divs, instead of the divs themselves, gets rid of any box model math. A nested div with side padding can also be used as an alternate method. */
        }
        a img { /* this selector removes the default blue border displayed in some browsers around an image when it is surrounded by a link */
            border: none;
        }
        /* ~~ Styling for your site's links must remain in this order - including the group of selectors that create the hover effect. ~~ */
        a:link {
            color: #42413C;
            text-decoration: underline; /* unless you style your links to look extremely unique, it's best to provide underlines for quick visual identification */
        }
        a:visited {
            color: #6E6C64;
            text-decoration: underline;
        }
        a:hover, a:active, a:focus { /* this group of selectors will give a keyboard navigator the same hover experience as the person using a mouse. */
            text-decoration: none;
        }

        .container {
            width: 960px;
            height: 42px;
            background: #FFF;
            margin: 0 auto; /* the auto value on the sides, coupled with the width, centers the layout */
        }

        .header {
            background: #FFBBFF;
            font-size:9px;
            position: relative;
        }

        .menu {
            background: #FFF0F5;
            padding: 0px 0;
            border: 0px solid;
        }

        .content {
            background: #FFF0F5;
            border: 0px solid;
            position: relative;
            width: 100%;
        }

        .footer {
            background: #FFBBFF;
            padding: 10px 0;
            border: 0px solid;
            position: relative;
        }

        .fltrt {  /* this class can be used to float an element right in your page. The floated element must precede the element it should be next to on the page. */
            float: right;
            margin-left: 8px;
        }
        .fltlft { /* this class can be used to float an element left in your page. The floated element must precede the element it should be next to on the page. */
            float: left;
            margin-right: 8px;
        }
        .clearfloat { /* this class can be placed on a <br /> or empty div as the final element following the last floated div (within the #container) if the #footer is removed or taken out of the #container */
            clear:both;
            height:0;
            font-size: 1px;
            line-height: 0px;
        }
        -->
    </style>
    <script src="SpryAssets/SpryMenuBar.js" type="text/javascript"></script>
    <link href="SpryAssets/SpryMenuBarHorizontal.css" rel="stylesheet" type="text/css" />
    <style type="text/css">
        body,td,th {
            color: #000;
        }
    </style>
</head>

<body>
    <div class="container">

        <div class="header">
            <a href="#"><img src="img/logo-200-60.png"  width="88" height="42px" id="Insert_logo" style="display:block;" /></a>
            <img src="img/busca.png" style='position:absolute; left:300px; top: 0px;'/>
            <img src="img/botao.png" width="38" style='position:absolute; left:570px; top: 0px;'/>
            <input name="txtbusca" type="text" border="0" id="txtbusca" value="Digite o que procura..." style="position:absolute; left:305px; top:8px; border:0"/>
            <img src="img/carrinho.png" style='position:absolute; left:850px; top: 2px;'/><a href="#" style="position:absolute; padding-left:890px; top:15px">Meu carrinho</a>
            <!-- end .header -->
        </div>
        <!--
        <div class="menu">
            <ul id="MenuBar1" class="MenuBarHorizontal">
                <li><a class="MenuBarItemSubmenu" href="#">Cão</a>
                    <ul>
                        <li><a href="#">Comida</a></li>
                        <li><a href="#">Roupa</a></li>
                        <li><a href="#">Brinquedo</a></li>
                    </ul>
                </li>
                <li><a href="#" class="MenuBarItemIE">Gato</a>
                    <ul>
                        <li><a href="#">Ração</a></li>
                    </ul>
                </li>
                <li class="MenuBarHorizontal"><a class="MenuBarItemSubmenu" href="#">Peixe</a>
                    <ul>
                        <li><a class="MenuBarItemSubmenu" href="#">Aquarios</a>
                            <ul>
                                <li><a href="#">Comida</a></li>
                                <li><a href="#">Equipamentos</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Peixes</a></li>
                        <li><a href="#">Limpeza</a></li>
                    </ul>
                </li>
                <li><a href="#">Papagaio</a></li>
                <li><a href="#">Serviços</a></li>
            </ul>
        </div>
        -->
        <div class="content">
            <?php echo $this->getContent(); ?>
        </div>

        <div class="footer">
            <a href="#"><img src="img/logo-200-60.png"  width="101" height="54" id="Insert_logo" style="display:block;" /></a>
            <!-- end .footer -->
        </div>

    </div>

    <script type="text/javascript">
        var MenuBar1 = new Spry.Widget.MenuBar("MenuBar1", {imgDown:"SpryAssets/SpryMenuBarDownHover.gif", imgRight:"SpryAssets/SpryMenuBarRightHover.gif"});
    </script>


</body>
</html>
